const mongoose = require("mongoose");

const ACTION_ENUM = [
  // Tenant lifecycle
  "tenant.created",
  "tenant.updated",
  "tenant.suspended",
  "tenant.activated",
  "tenant.cancelled",
  "tenant.plan_changed",
  "tenant.limit_changed",
  "tenant.deleted",
  // User admin actions
  "user.created_by_superadmin",
  "user.deleted_by_superadmin",
  // Generic CRUD (auto-generated by audit middleware)
  "GET_SETTINGS",
  "GET_PRODUCTS",
  "POST_PRODUCTS",
  "PUT_PRODUCTS",
  "PATCH_PRODUCTS",
  "DELETE_PRODUCTS",
  "GET_PURCHASES",
  "POST_PURCHASES",
  "PUT_PURCHASES",
  "DELETE_PURCHASES",
  "GET_SALES",
  "POST_SALES",
  "PUT_SALES",
  "DELETE_SALES",
  "GET_CLIENTS",
  "POST_CLIENTS",
  "PUT_CLIENTS",
  "DELETE_CLIENTS",
  "GET_SUPPLIES",
  "POST_SUPPLIES",
  "PUT_SUPPLIES",
  "DELETE_SUPPLIES",
  "GET_RECIPES",
  "POST_RECIPES",
  "PUT_RECIPES",
  "DELETE_RECIPES",
  "GET_STOCKMOVEMENTS",
  "POST_STOCKMOVEMENTS",
  "GET_SUPPLIERS",
  "POST_SUPPLIERS",
  "PUT_SUPPLIERS",
  "DELETE_SUPPLIERS",
  "GET_USERS",
  "POST_USERS",
  "DELETE_USERS",
  "GET_DASHBOARD",
  "GET_REPORTS",
  "GET_AUDITLOGS",
];

const auditLogSchema = new mongoose.Schema(
  {
    action: {
      type: String,
      required: true,
      enum: ACTION_ENUM,
    },

    // Who performed the action (user or admin)
    admin: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: false,
    },

    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    userEmail: {
      type: String,
    },

    // Which tenant was affected (if applicable)
    tenant: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Tenant",
    },

    // HTTP context
    method: {
      type: String,
      enum: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    },
    path: {
      type: String,
    },
    statusCode: {
      type: Number,
    },
    resourceType: {
      type: String,
    },
    resourceId: {
      type: String,
    },

    // Details of the action
    details: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    // HTTP Request info
    ip: {
      type: String,
    },
    userAgent: {
      type: String,
    },
    requestId: {
      type: String,
    },

    // For filtering by date range
    timestamp: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true },
);

// Indexes for efficient querying
auditLogSchema.index({ action: 1 });
auditLogSchema.index({ admin: 1 });
auditLogSchema.index({ tenant: 1 });
auditLogSchema.index({ timestamp: -1 });
auditLogSchema.index({ createdAt: -1 });

module.exports = mongoose.model("AuditLog", auditLogSchema);
